<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="D11-KamalKant.local" ignored="0" name="Free CRM App Test Cases" tests="85" failures="18" timestamp="01 Oct 2020 06:03:41 GMT" time="41.052" errors="0">
  <testcase name="getRestaurantReviewNegativeCases" time="2.79" classname="tests.restaurant.RestaurantApiTest">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at apiCalls.Location.getRestaurantReview(Location.java:80)
at tests.restaurant.RestaurantApiTest.getRestaurantReviewNegativeCases(RestaurantApiTest.java:69)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getRestaurantReviewNegativeCases -->
  <testcase name="searchByInvalidLocation" time="3.621" classname="tests.restaurant.SearchApiTest">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at apiCalls.Location.searchRestaurant(Location.java:56)
at tests.restaurant.SearchApiTest.searchByInvalidLocation(SearchApiTest.java:41)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- searchByInvalidLocation -->
  <testcase name="getRestaurantReviewNegativeCases" time="1.299" classname="tests.restaurant.RestaurantApiTest">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at apiCalls.Location.getRestaurantReview(Location.java:80)
at tests.restaurant.RestaurantApiTest.getRestaurantReviewNegativeCases(RestaurantApiTest.java:69)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getRestaurantReviewNegativeCases -->
  <testcase name="searchByCoordinate" time="4.322" classname="tests.restaurant.SearchApiTest"/>
  <testcase name="searchByLocation" time="1.246" classname="tests.restaurant.SearchApiTest"/>
  <testcase name="getRestaurantWithInvalidLocation" time="0.814" classname="tests.location.RestaurantInLocation"/>
  <testcase name="getRestaurantReviewNegativeCases" time="1.134" classname="tests.restaurant.RestaurantApiTest">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at apiCalls.Location.getRestaurantReview(Location.java:80)
at tests.restaurant.RestaurantApiTest.getRestaurantReviewNegativeCases(RestaurantApiTest.java:69)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getRestaurantReviewNegativeCases -->
  <testcase name="getRestaurantWithInvalidLocation" time="0.866" classname="tests.location.RestaurantInLocation"/>
  <testcase name="searchByLocation" time="1.363" classname="tests.restaurant.SearchApiTest"/>
  <testcase name="getRestaurantWithLocation" time="1.333" classname="tests.location.RestaurantInLocation"/>
  <testcase name="getRestaurantWithInvalidLocation" time="0.937" classname="tests.location.RestaurantInLocation"/>
  <testcase name="searchByLocation" time="1.374" classname="tests.restaurant.SearchApiTest"/>
  <testcase name="getRestaurantWithLocation" time="1.081" classname="tests.location.RestaurantInLocation"/>
  <testcase name="getRestaurantWithInvalidLocation" time="0.959" classname="tests.location.RestaurantInLocation"/>
  <testcase name="searchByLocation" time="1.21" classname="tests.restaurant.SearchApiTest"/>
  <testcase name="getRestaurantWithLocation" time="1.28" classname="tests.location.RestaurantInLocation"/>
  <testcase name="getRestaurantWithMissingParam" time="1.036" classname="tests.location.RestaurantInLocation"/>
  <testcase name="getLocationMissingParam" time="0.835" classname="tests.location.LocationAPITests">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at apiCalls.Location.getLocation(Location.java:32)
at tests.location.LocationAPITests.getLocationMissingParam(LocationAPITests.java:61)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getLocationMissingParam -->
  <testcase name="getRestaurantWithMissingParam" time="0.905" classname="tests.location.RestaurantInLocation"/>
  <testcase name="getRestaurantWithLocation" time="1.099" classname="tests.location.RestaurantInLocation"/>
  <testcase name="getRestaurantWithMissingParam" time="0.819" classname="tests.location.RestaurantInLocation"/>
  <testcase name="getLocationMissingParam" time="1.078" classname="tests.location.LocationAPITests">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at apiCalls.Location.getLocation(Location.java:32)
at tests.location.LocationAPITests.getLocationMissingParam(LocationAPITests.java:69)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getLocationMissingParam -->
  <testcase name="getLocationWithCoordinate" time="1.143" classname="tests.location.LocationAPITests"/>
  <testcase name="getRestaurantWithMissingParam" time="0.943" classname="tests.location.RestaurantInLocation"/>
  <testcase name="getLocationMissingParam" time="0.915" classname="tests.location.LocationAPITests">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at apiCalls.Location.getLocation(Location.java:32)
at tests.location.LocationAPITests.getLocationMissingParam(LocationAPITests.java:69)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getLocationMissingParam -->
  <testcase name="getLocationWithCoordinate" time="0.9" classname="tests.location.LocationAPITests"/>
  <testcase name="getLocationWithName" time="0.962" classname="tests.location.LocationAPITests"/>
  <testcase name="getCategoriesTest" time="1.098" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getLocationWithCoordinate" time="1.014" classname="tests.location.LocationAPITests"/>
  <testcase name="getRestaurantById" time="13.095" classname="tests.restaurant.RestaurantApiTest"/>
  <testcase name="getRestaurantReview" time="13.244" classname="tests.restaurant.RestaurantApiTest"/>
  <testcase name="getLocationWithName" time="0.953" classname="tests.location.LocationAPITests">
    <failure type="java.lang.AssertionError" message="expected [zomato_place] but found [city]">
      <![CDATA[java.lang.AssertionError: expected [zomato_place] but found [city]
at tests.location.LocationAPITests.validateLocationData(LocationAPITests.java:74)
at tests.location.LocationAPITests.getLocationWithName(LocationAPITests.java:44)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getLocationWithName -->
  <testcase name="getCitiesWithInvalidLocation" time="0.937" classname="tests.commonAPI.CommonAPITests">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at apiCalls.Common.getCities(Common.java:48)
at tests.commonAPI.CommonAPITests.getCitiesWithInvalidLocation(CommonAPITests.java:174)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getCitiesWithInvalidLocation -->
  <testcase name="getLocationWithCoordinate" time="1.113" classname="tests.location.LocationAPITests"/>
  <testcase name="getCityWithDiffCount" time="1.134" classname="tests.commonAPI.CommonAPITests">
    <failure type="java.lang.AssertionError" message="expected [0] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [10]
at tests.commonAPI.CommonAPITests.getCityWithDiffCount(CommonAPITests.java:86)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getCityWithDiffCount -->
  <testcase name="getCityWithDiffParam" time="0.855" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getLocationWithName" time="1.095" classname="tests.location.LocationAPITests"/>
  <testcase name="getCityWithIdAndName" time="0.909" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithDiffCount" time="1.047" classname="tests.commonAPI.CommonAPITests">
    <failure type="java.lang.AssertionError" message="expected [11] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [11] but found [10]
at tests.commonAPI.CommonAPITests.getCityWithDiffCount(CommonAPITests.java:86)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getCityWithDiffCount -->
  <testcase name="getCityWithDiffParam" time="0.984" classname="tests.commonAPI.CommonAPITests">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
at tests.commonAPI.CommonAPITests.getCityWithDiffParam(CommonAPITests.java:77)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getCityWithDiffParam -->
  <testcase name="getLocationWithName" time="1.032" classname="tests.location.LocationAPITests"/>
  <testcase name="getCityWithDiffCount" time="0.823" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithIdAndName" time="1.177" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithDiffParam" time="0.795" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithIdOnly" time="0.817" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithIdAndName" time="0.746" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithDiffParam" time="0.786" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithInvalidIdNameCombination" time="0.875" classname="tests.commonAPI.CommonAPITests">
    <failure type="java.lang.AssertionError" message="expected [0] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [1]
at tests.commonAPI.CommonAPITests.getCityWithInvalidIdNameCombination(CommonAPITests.java:134)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getCityWithInvalidIdNameCombination -->
  <testcase name="getCityWithIdOnly" time="0.724" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithDiffParam" time="0.869" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithIdAndName" time="0.976" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithInvalidQParam" time="0.89" classname="tests.commonAPI.CommonAPITests">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at apiCalls.Common.getCities(Common.java:48)
at tests.commonAPI.CommonAPITests.getCityWithInvalidQParam(CommonAPITests.java:93)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getCityWithInvalidQParam -->
  <testcase name="getCityWithIdOnly" time="0.939" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithInvalidQParam" time="0.784" classname="tests.commonAPI.CommonAPITests">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at apiCalls.Common.getCities(Common.java:48)
at tests.commonAPI.CommonAPITests.getCityWithInvalidQParam(CommonAPITests.java:93)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getCityWithInvalidQParam -->
  <testcase name="getCityWithDiffParam" time="0.839" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithLocation" time="0.889" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithIdOnly" time="0.952" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithDiffParam" time="0.745" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithName" time="0.803" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithLocation" time="0.955" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCollectionWithCityId" time="0.847" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithName" time="0.996" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithDiffParam" time="1.062" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithLocation" time="1.086" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCollectionWithCityId" time="1.068" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithName" time="0.823" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithDiffParam" time="0.856" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithLocation" time="0.908" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCollectionWithCityId" time="0.977" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithDiffParam" time="0.695" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithName" time="0.847" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCollectionWithInvalidCityId" time="0.808" classname="tests.commonAPI.CommonAPITests">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at apiCalls.Common.getCollection(Common.java:60)
at tests.commonAPI.CommonAPITests.getCollectionWithInvalidCityId(CommonAPITests.java:181)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getCollectionWithInvalidCityId -->
  <testcase name="getCollectionWithCityId" time="0.881" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getRestaurantById" time="9.899" classname="tests.restaurant.RestaurantApiTest"/>
  <testcase name="getCollectionWithInvalidLocation" time="0.833" classname="tests.commonAPI.CommonAPITests">
    <failure type="java.lang.AssertionError" message="expected [400] but found [500]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [500]
at apiCalls.Common.getCollection(Common.java:60)
at tests.commonAPI.CommonAPITests.getCollectionWithInvalidLocation(CommonAPITests.java:166)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getCollectionWithInvalidLocation -->
  <testcase name="getCityWithDiffParam" time="0.939" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCollectionWithInvalidQParam" time="0.732" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCollectionWithLocation" time="0.723" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCityWithDiffParam" time="0.813" classname="tests.commonAPI.CommonAPITests">
    <failure type="java.lang.AssertionError" message="expected [0] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [3]
at tests.commonAPI.CommonAPITests.getCityWithDiffParam(CommonAPITests.java:77)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getCityWithDiffParam -->
  <testcase name="getCollectionWithInvalidQParam" time="0.957" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCollectionWithLocation" time="0.886" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCollectionWithLocation" time="0.92" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getCollectionWithLocation" time="0.78" classname="tests.commonAPI.CommonAPITests"/>
  <testcase name="getRestaurantById" time="8.943" classname="tests.restaurant.RestaurantApiTest"/>
  <testcase name="getRestaurantById" time="9.093" classname="tests.restaurant.RestaurantApiTest"/>
</testsuite> <!-- Free CRM App Test Cases -->
